version: '3' # composeファイルのバーション指定
services:
  go: # service名
    build: ./server # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - ./server:/go/src/app # マウントディレクトリ指定
    ports:
      - "8080:8080"
  node:
    build: ./front
    tty: true # コンテナの起動永続化
    volumes:
      - ./front:/app # マウントディレクトリ指定

